# Site settings
title: COMP4431 Course Notes
description: My notes for COMP4431 - Multimedia Computing
author: Iris Chen
email: your.email@connect.polyu.hk

# Build settings
remote_theme: just-the-docs/just-the-docs
# Navigation
nav_enabled: true
search_enabled: true

# Color scheme
color_scheme: light

# Markdown settings
markdown: kramdown
kramdown:
  parse_block_html: true
# URL settings
baseurl: "/comp4431-notes"
url: "https://irischen04.github.io"

# Navigation
header_pages:
  - lec1.md
  - lec2.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
